using Content.Client._KS14.UI; // KS14
using System.Numerics;
using System.Text;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class DockingScreen : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly SharedShuttleSystem _shuttles;

    /// <summary>
    /// Stored by GridID then by docks
    /// </summary>
    public Dictionary<NetEntity, List<DockingPortState>> Docks = new();

    /// <summary>
    /// Store the dock buttons for the side buttons.
    /// </summary>
    private readonly Dictionary<NetEntity, Button> _ourDockButtons = new();

    public event Action<NetEntity, NetEntity>? DockRequest;
    public event Action<NetEntity>? UndockRequest;

    public DockingScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _shuttles = _entManager.System<SharedShuttleSystem>();

        DockingControl.OnViewDock += OnView;
        DockingControl.DockRequest += (entity, netEntity) =>
        {
            DockRequest?.Invoke(entity, netEntity);
        };
        DockingControl.UndockRequest += entity =>
        {
            UndockRequest?.Invoke(entity);
        };

        // KS14: instrument look (cosmetic only - see KsInstrumentDressing).
        KsInstrumentDressing.Apply(this, KsInstrumentPalette.Map);
    }

    private void OnView(NetEntity obj)
    {
        if (_ourDockButtons.TryGetValue(obj, out var viewed))
        {
            viewed.Pressed = true;
        }
    }

    public void UpdateState(EntityUid? shuttle, DockingInterfaceState state)
    {
        Docks = state.Docks;
        DockingControl.DockState = state;
        DockingControl.GridEntity = shuttle;
        BuildDocks(shuttle);
    }

    private void BuildDocks(EntityUid? shuttle)
    {
        DockingControl.BuildDocks(shuttle);
        var currentDock = DockingControl.ViewedDock;
        DockPorts.DisposeAllChildren();
        _ourDockButtons.Clear();

        if (shuttle == null)
        {
            DockingControl.SetViewedDock(null);
            return;
        }

        var shuttleNent = _entManager.GetNetEntity(shuttle.Value);

        if (!Docks.TryGetValue(shuttleNent, out var shuttleDocks) || shuttleDocks.Count <= 0)
            return;

        var dockText = new StringBuilder();
        var buttonGroup = new ButtonGroup();
        var dockIndex = 0;
        var selected = false;

        // Build a status row for each of our docks. The main button still selects the
        // port for map-based docking, while a docked port can be undocked directly.
        foreach (var dock in shuttleDocks)
        {
            dockIndex++;
            dockText.Clear();
            dockText.Append(Loc.GetString("shuttle-console-dock-entry", ("index", dockIndex)));
            dockText.AppendLine();
            dockText.Append(GetDockStatus(dock));

            var button = new Button()
            {
                Text = dockText.ToString(),
                ToggleMode = true,
                Group = buttonGroup,
                Margin = new Thickness(0f, 3f),
                HorizontalExpand = true,
                ToolTip = dock.Name,
            };

            button.OnMouseEntered += args =>
            {
                DockingControl.HighlightedDock = dock.Entity;
            };

            button.OnMouseExited += args =>
            {
                DockingControl.HighlightedDock = null;
            };

            button.Label.Margin = new Thickness(3f);

            if (currentDock == dock.Entity)
            {
                selected = true;
                button.Pressed = true;
            }

            button.OnPressed += args =>
            {
                OnDockPress(dock);
            };

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            _ourDockButtons[dock.Entity] = button;
            row.AddChild(button);

            if (dock.Connected)
            {
                var undockButton = new Button
                {
                    Text = Loc.GetString("shuttle-console-undock"),
                    Margin = new Thickness(4f, 3f, 0f, 3f),
                    VerticalAlignment = VAlignment.Stretch,
                };

                undockButton.OnPressed += _ =>
                {
                    UndockRequest?.Invoke(dock.Entity);
                };

                row.AddChild(undockButton);
            }

            DockPorts.AddChild(row);
        }

        // Button group needs one selected so just show the first one.
        if (!selected)
        {
            var buttonOne = shuttleDocks[0];
            OnDockPress(buttonOne);
        }
    }

    private string GetDockStatus(DockingPortState dock)
    {
        if (dock.GridDockedWith == null)
            return Loc.GetString("shuttle-console-dock-status-undocked");

        var grid = _entManager.GetEntity(dock.GridDockedWith);
        var name = _entManager.EntityExists(grid)
            ? _shuttles.GetIFFLabel(grid.Value)
            : null;

        return Loc.GetString("shuttle-console-dock-status-docked",
            ("name", name ?? Loc.GetString("shuttle-console-unknown")));
    }

    private void OnDockPress(DockingPortState state)
    {
        DockingControl.SetViewedDock(state);
    }
}
