using System.Numerics;
using Content.Client._Crescent.Shuttle;
using Content.Client._KS14.UI; // KS14
using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar; // KS14
using Content.Client._Crescent.ShipShields; // KS14: status strip
using Robust.Client.Graphics; // KS14
using Robust.Shared.Configuration; // KS14
using Robust.Shared.Timing; // KS14
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class ShuttleConsoleWindow : KsBaseWindow, // KS14: instrument shell
    IComputerWindow<ShuttleBoundUserInterfaceState>
{
    /// <summary>KS14: edge width (px) that grabs a resize instead of a move, matching FancyWindow's feel.</summary>
    private const int DragMarginSize = 7;

    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly ILogManager _mills = default!;
    [Dependency] private readonly IGameTiming _timing = default!; // KS14
    [Dependency] private readonly IConfigurationManager _cfg = default!; // KS14

    /// <summary>KS14: when the shell was created; drives the power-on blink.</summary>
    private TimeSpan _bootStartedAt = TimeSpan.MinValue;

    /// <summary>KS14: when the crew last switched tabs; drives the interlace blink.</summary>
    private TimeSpan _tabSwitchedAt = TimeSpan.MinValue;

    /// <summary>KS14: the grid whose status the strip reports; set from the nav state.</summary>
    private EntityUid? _statusGrid;

    /// <summary>
    ///     KS14: whether the ship is being hit, straight from the server. It covers any damage
    ///         to anything on the grid, so unlike the shield reading it replaces it keeps
    ///         warning after the shield collapses, and works on hulls with no shield at all.
    /// </summary>
    private bool _takingFire;

    private ShuttleConsoleMode _mode = ShuttleConsoleMode.Nav;

    public event Action<NetEntity, NetEntity>? DockRequest;
    public event Action<NetEntity>? UndockRequest;


    public ShuttleConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Mode switching
        NavModeButton.OnPressed += NavPressed;
        MapModeButton.OnPressed += MapPressed;
        DockModeButton.OnPressed += DockPressed;

        // Modes are exclusive
        var group = new ButtonGroup();

        NavModeButton.Group = group;
        MapModeButton.Group = group;
        DockModeButton.Group = group;

        NavModeButton.Pressed = true;
        SetupMode(_mode);

        KsSetupChrome(); // KS14
        _bootStartedAt = _timing.CurTime; // KS14: power-on blink

        DockContainer.DockRequest += (entity, netEntity) =>
        {
            DockRequest?.Invoke(entity, netEntity);
        };

        DockContainer.UndockRequest += entity =>
        {
            UndockRequest?.Invoke(entity);
        };

        NfInitialize(); // Frontier Initialization for the ShuttleConsoleWindow
        HullrotInitialize(group);
    }

    private void ClearModes(ShuttleConsoleMode mode)
    {
        if (mode != ShuttleConsoleMode.Nav)
        {
            NavContainer.Visible = false;
        }

        if (mode != ShuttleConsoleMode.Map)
        {
            MapContainer.Visible = false;
            MapContainer.SetMap(MapId.Nullspace, Vector2.Zero);
        }

        if (mode != ShuttleConsoleMode.Dock)
        {
            DockContainer.Visible = false;
        }

        if (mode != ShuttleConsoleMode.Crew)
        {
            CrewContainer.Visible = false;
        }
    }

    private void NavPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Nav);
    }

    private void MapPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Map);
    }

    private void DockPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Dock);
    }

    private void SetupMode(ShuttleConsoleMode mode)
    {
        switch (mode)
        {
            case ShuttleConsoleMode.Nav:
                NavContainer.Visible = true;
                break;
            case ShuttleConsoleMode.Map:
                MapContainer.Visible = true;
                MapContainer.Startup();
                break;
            case ShuttleConsoleMode.Dock:
                DockContainer.Visible = true;
                break;
            case ShuttleConsoleMode.Crew:
                CrewContainer.Visible = true;
                break;
            default:
                throw new NotImplementedException();
        }
    }

    public void SwitchMode(ShuttleConsoleMode mode)
    {
        if (_mode == mode)
            return;

        _mode = mode;
        ClearModes(mode);
        SetupMode(_mode);
        _tabSwitchedAt = _timing.CurTime; // KS14: interlace blink
    }

    public enum ShuttleConsoleMode : byte
    {
        Nav,
        Map,
        Dock,
        Crew,
    }

    public void UpdateState(EntityUid owner, ShuttleBoundUserInterfaceState cState)
    {
        //_mills.GetSawmill("ui-debug-crescent").Warning($"Got interface state with bytes toggled {cState.DirtyFlags}");
        if((cState.DirtyFlags & StateDirtyFlags.IFF) != 0)
        {
            NavScreen.UpdateState(cState.IFFState!);
            _takingFire = cState.IFFState!.TakingFire; // KS14: rides the fast path
        }
        if ((cState.DirtyFlags & StateDirtyFlags.Base) == 0)
            return;
        var coordinates = _entManager.GetCoordinates(cState.NavState!.Coordinates);
        if ((cState.DirtyFlags & StateDirtyFlags.Dock) != 0 || DockContainer.Docks.Count == 0)
        {
            DockContainer.UpdateState(coordinates?.EntityId, cState.DockState!);
            //_mills.GetSawmill("ui-debug-crescent").Warning($"Update dock with {cState.DockState!.Docks.Count} docks");
        }

        _statusGrid = coordinates?.EntityId; // KS14: status strip
        NavContainer.SetShuttle(coordinates?.EntityId);
        MapContainer.SetShuttle(coordinates?.EntityId);
        MapContainer.SetConsole(owner);
        CrewManagementButton.Disabled = !cState.canAccesCrew;
        if(_mode == ShuttleConsoleMode.Crew && CrewManagementButton.Disabled)
            SwitchMode(ShuttleConsoleMode.Map);


        CrewContainer.UpdateState(cState.CrewState!);
        NavContainer.UpdateState(cState.NavState);
        MapContainer.UpdateState(cState.MapState!);
    }

    /// <summary>
    ///     KS14: paints the instrument shell. The stock FancyWindow chrome is gone, so the
    ///         bezel, title bar and close button are drawn here from
    ///         <see cref="KsInstrumentChrome"/>. Purely cosmetic - no screen behaviour hangs
    ///         off any of it.
    /// </summary>
    private void KsSetupChrome()
    {
        KsInstrumentSheetlet.MakeInstrument(
            NavModeButton, MapModeButton, DockModeButton, CrewManagementButton, CloseChromeButton);

        Bezel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = KsInstrumentChrome.WindowBackground,
            BorderColor = KsInstrumentChrome.WindowBorder,
            BorderThickness = new Thickness(2),
        };

        TitleBar.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = KsInstrumentChrome.TitleBackground,
            BorderColor = KsInstrumentChrome.WindowBorder,
            BorderThickness = new Thickness(0, 0, 0, 1),
        };

        TitleLabel.FontColorOverride = KsInstrumentChrome.TitleText;

        foreach (var separator in new[] { Sep1, Sep2, Sep3 })
        {
            separator.FontColorOverride = KsInstrumentPalette.Shell.AccentDim;
        }

        StatusStrip.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = KsInstrumentPalette.Shell.Background,
            BorderColor = KsInstrumentPalette.Shell.AccentDim,
            BorderThickness = new Thickness(1),
        };

        CloseChromeButton.OnPressed += _ => Close();
    }

    /// <summary>
    ///     KS14: BaseWindow has no chrome of its own, so the whole surface drags and the
    ///         outer <see cref="DragMarginSize"/> band resizes.
    /// </summary>
    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        var mode = DragMode.Move;

        if (!Resizable)
            return mode;

        if (relativeMousePos.Y < DragMarginSize)
            mode = DragMode.Top;
        else if (relativeMousePos.Y > Size.Y - DragMarginSize)
            mode = DragMode.Bottom;

        if (relativeMousePos.X < DragMarginSize)
            mode |= DragMode.Left;
        else if (relativeMousePos.X > Size.X - DragMarginSize)
            mode |= DragMode.Right;

        return mode;
    }

    /// <summary>
    ///     KS14: the shell's two cosmetic blinks - a power-on flicker when the console opens
    ///         and a short interlace flicker on a tab switch. Both only modulate
    ///         <c>Contents</c>, so nothing below is aware of them, and both are skipped
    ///         entirely under <c>accessibility.reduced_motion</c>.
    /// </summary>
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var reduced = _cfg.GetCVar(CCVars.ReducedMotion);

        // The power-on blink wins over the tab blink while it runs.
        if (_bootStartedAt != TimeSpan.MinValue)
        {
            var bootSince = (_timing.CurTime - _bootStartedAt).TotalSeconds;
            if (bootSince < KsInstrumentAnim.BootDuration && !reduced)
            {
                Contents.Modulate = Color.White.WithAlpha(KsInstrumentAnim.BootBrightness(bootSince));
                return;
            }

            Contents.Modulate = Color.White;
            _bootStartedAt = TimeSpan.MinValue;
        }

        KsRefreshStatusStrip();

        if (_tabSwitchedAt == TimeSpan.MinValue)
            return;

        var since = (_timing.CurTime - _tabSwitchedAt).TotalSeconds;
        if (since < KsInstrumentAnim.TabFlickerDuration && !reduced)
        {
            Contents.Modulate = Color.White.WithAlpha(KsInstrumentAnim.TabBrightness(since));
        }
        else
        {
            Contents.Modulate = Color.White;
            _tabSwitchedAt = TimeSpan.MinValue;
        }
    }

    /// <summary>
    ///     KS14: the always-on status strip. Reads the ship's shield emitter straight off the
    ///         grid - every field it needs is already networked, so this costs no extra server
    ///         state - and latches a TAKING FIRE warning whenever the shield's damage total
    ///         climbs between frames.
    /// </summary>
    private void KsRefreshStatusStrip()
    {
        if (_statusGrid is not { } grid)
        {
            StatusLabel.Text = Loc.GetString("ks-status-shield-none");
            AlertLabel.Visible = false;
            return;
        }

        var shield = ShipShieldReadout.Find(_entManager, grid);

        if (shield == null)
        {
            StatusLabel.Text = Loc.GetString("ks-status-shield-none");
            StatusLabel.FontColorOverride = KsInstrumentPalette.Shell.TextDim;
            KsSetTakingFire();
            return;
        }

        if (ShipShieldReadout.IsDown(shield))
        {
            StatusLabel.Text = Loc.GetString("ks-status-shield-down",
                ("time", (int) ShipShieldReadout.DownSeconds(shield)));
            StatusLabel.FontColorOverride = KsInstrumentPalette.Shell.Warning;
        }
        else
        {
            // Percent, so the strip reads the same on every hull no matter its damage limit.
            StatusLabel.Text = Loc.GetString("ks-status-shield-up",
                ("percent", ShipShieldReadout.Percent(shield)));
            StatusLabel.FontColorOverride = KsInstrumentPalette.Shell.Text;
        }

        KsSetTakingFire();
    }

    /// <summary>KS14: shows or hides the TAKING FIRE warning from the server's grid damage flag.</summary>
    private void KsSetTakingFire()
    {
        AlertLabel.Visible = _takingFire;
        if (!_takingFire)
            return;

        AlertLabel.Text = Loc.GetString("ks-status-alert-taking-fire");
        AlertLabel.FontColorOverride = KsInstrumentPalette.Shell.Warning;
    }
}
