using Content.Client.UserInterface.Systems.Actions.Controls;
using Content.Shared.CCVar;
using Content.Shared.Input;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;

namespace Content.Client.UserInterface.Systems.Actions.Widgets;

[GenerateTypedNameReferences]
public sealed partial class ActionsBar : UIWidget
{
    /// <summary>
    /// Side of a single action slot.
    /// </summary>
    private const float SlotSize = 64f;

    private const float ScreenEdgeMargin = SlotSize;

    /// <summary>
    /// Screen space kept free below the vertical bar so it does not run into the bottom left inventory.
    /// </summary>
    private const float VerticalBottomMargin = 128f;

    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    private bool? _vertical;
    private float _gridLimit;

    public ActionsBar()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var keys = ContentKeyFunctions.GetHotbarBoundKeys();
        for (var index = 1; index < keys.Length; index++)
            ActionsContainer.Children.Add(MakeButton(index));
        ActionsContainer.Children.Add(MakeButton(0));

        ActionButton MakeButton(int index)
        {
            var boundKey = keys[index];
            var button = new ActionButton(_entity);
            button.KeyBind = boundKey;
            button.Label.Text = index.ToString();
            return button;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var vertical = _cfg.GetCVar(CCVars.HudActionBarVertical);
        if (_vertical != vertical)
        {
            _vertical = vertical;
            _gridLimit = 0f;
        }

        UpdateGridLimit(vertical);
    }

    /// <summary>
    /// Fits the action grid into the remaining screen space. Horizontal mode fills rows and wraps down;
    /// vertical mode fills columns and wraps right.
    /// </summary>
    private void UpdateGridLimit(bool vertical)
    {
        var rootSize = UserInterfaceManager.RootControl.Size;
        var available = vertical
            ? rootSize.Y - GlobalPosition.Y - VerticalBottomMargin
            : rootSize.X - GlobalPosition.X - ScreenEdgeMargin;
        available = MathF.Max(available, SlotSize);

        if (MathF.Abs(available - _gridLimit) < 1f)
            return;

        _gridLimit = available;
        if (vertical)
            ActionsContainer.MaxGridHeight = available;
        else
            ActionsContainer.MaxGridWidth = available;
    }
}
