using Content.Client.UserInterface.Controls;
using Content.Shared.Power;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Power.Storage;

[GenerateTypedNameReferences]
public sealed partial class PowerStorageControlWindow : FancyWindow
{
    private bool _inputEnabled;
    private bool _outputEnabled;
    private int _maxInputKilowatts;
    private int _maxOutputKilowatts;

    public event Action<bool>? OnInputEnabled;
    public event Action<bool>? OnOutputEnabled;
    public event Action<float>? OnInputLimit;
    public event Action<float>? OnOutputLimit;

    public PowerStorageControlWindow()
    {
        RobustXamlLoader.Load(this);

        InputLimit.IsValid += value => value >= 0 && value <= _maxInputKilowatts;
        OutputLimit.IsValid += value => value >= 0 && value <= _maxOutputKilowatts;

        InputLimit.ValueChanged += args => OnInputLimit?.Invoke(args.Value * 1000f);
        OutputLimit.ValueChanged += args => OnOutputLimit?.Invoke(args.Value * 1000f);
        InputToggle.OnPressed += _ => OnInputEnabled?.Invoke(!_inputEnabled);
        OutputToggle.OnPressed += _ => OnOutputEnabled?.Invoke(!_outputEnabled);
    }

    public void SetEntity(EntityUid entity)
    {
        EntityView.SetEntity(entity);
    }

    public void UpdateState(PowerStorageControlState state)
    {
        _inputEnabled = state.InputEnabled;
        _outputEnabled = state.OutputEnabled;
        _maxInputKilowatts = (int) MathF.Ceiling(state.MaxInputLimit / 1000f);
        _maxOutputKilowatts = (int) MathF.Ceiling(state.MaxOutputLimit / 1000f);

        var charge = state.MaxCharge > 0f
            ? Math.Clamp(state.CurrentCharge / state.MaxCharge, 0f, 1f)
            : 0f;

        ChargeBar.Value = charge;
        ChargePercentage.Text = charge.ToString("P0");
        StoredEnergy.Text = Loc.GetString(
            "power-storage-control-window-stored-energy",
            ("stored", state.CurrentCharge),
            ("capacity", state.MaxCharge));

        InputVoltage.Text = Loc.GetString(GetVoltageLocId(state.InputVoltage));
        OutputVoltage.Text = Loc.GetString(GetVoltageLocId(state.OutputVoltage));
        InputCurrent.Text = Loc.GetString("power-storage-control-window-power-value", ("power", state.CurrentInput));
        OutputCurrent.Text = Loc.GetString("power-storage-control-window-power-value", ("power", state.CurrentOutput));
        InputMaximum.Text = Loc.GetString("power-storage-control-window-maximum", ("power", state.MaxInputLimit));
        OutputMaximum.Text = Loc.GetString("power-storage-control-window-maximum", ("power", state.MaxOutputLimit));

        if (!InputLimit.LineEditControl.HasKeyboardFocus())
            InputLimit.OverrideValue((int) MathF.Round(state.InputLimit / 1000f));

        if (!OutputLimit.LineEditControl.HasKeyboardFocus())
            OutputLimit.OverrideValue((int) MathF.Round(state.OutputLimit / 1000f));

        UpdateToggle(InputToggle, state.InputEnabled);
        UpdateToggle(OutputToggle, state.OutputEnabled);
    }

    private static LocId GetVoltageLocId(PowerStorageVoltage voltage)
    {
        return voltage switch
        {
            PowerStorageVoltage.High => "power-storage-control-voltage-high",
            PowerStorageVoltage.Medium => "power-storage-control-voltage-medium",
            PowerStorageVoltage.Low => "power-storage-control-voltage-low",
            _ => throw new ArgumentOutOfRangeException(nameof(voltage), voltage, null),
        };
    }

    private static void UpdateToggle(Robust.Client.UserInterface.Controls.Button button, bool enabled)
    {
        button.Text = Loc.GetString(enabled
            ? "power-storage-control-window-enabled"
            : "power-storage-control-window-disabled");
        button.SetOnlyStyleClass(enabled ? "Good" : "Danger");
    }
}
