using System.Globalization;
using System.Linq;
using Content.Client._Crescent.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Crescent.Taxation;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Crescent.Taxation;

[GenerateTypedNameReferences]
public sealed partial class TaxationConsoleWindow : FancyWindow
{
    /// <summary>Raised with a fraction (0..1) when the operator sets the default rate.</summary>
    public event Action<float>? OnSetDefault;

    /// <summary>Raised with (protoId, fraction 0..1) when the operator sets a per-good override.</summary>
    public event Action<(string ProtoId, float Rate)>? OnSetOverride;

    /// <summary>Raised with a protoId when the operator clears a per-good override.</summary>
    public event Action<string>? OnClearOverride;

    private readonly ConsoleRowList<string, GoodRow> _rows;
    private readonly List<TaxableGoodEntry> _visible = new();

    private bool _canEdit;
    private TaxationConsoleState? _state;

    public TaxationConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("taxation-console-title");

        _rows = new ConsoleRowList<string, GoodRow>(GoodsContainer, () => new GoodRow(this));

        DefaultSetButton.OnPressed += _ => ApplyDefaultRate();
        // Enter applies it too; the box used to swallow the key and leave the typed rate unsent.
        DefaultRateEdit.OnTextEntered += _ => ApplyDefaultRate();

        // Filtering is local, so it re-runs against the last state instead of waiting for the next push.
        FilterEdit.OnTextChanged += _ => RefreshRows();
    }

    /// <summary>
    ///     Sends the station-wide default rate and puts the box back in step with what was sent. A rate
    ///     that does not parse is left where it was typed, still tinted as pending, rather than being
    ///     silently rewritten to the live one.
    /// </summary>
    private void ApplyDefaultRate()
    {
        if (!TryParsePercent(DefaultRateEdit.Text, out var rate))
            return;

        DefaultRateEdit.SetSubmitted(ToPercentString(rate));
        OnSetDefault?.Invoke(rate);
    }

    public void UpdateState(TaxationConsoleState state)
    {
        _state = state;
        _canEdit = state.CanEdit;

        TreasuryLabel.SetTextIfChanged(Loc.GetString("taxation-console-treasury", ("balance", state.Treasury)));

        AccessLabel.SetTextIfChanged(Loc.GetString(state.CanEdit
            ? "taxation-console-access-granted"
            : "taxation-console-access-view"));
        AccessLabel.FontColorOverride = state.CanEdit ? ConsolePalette.Good : ConsolePalette.Muted;

        DefaultRateEdit.SetValue(ToPercentString(state.DefaultRate));
        DefaultRateEdit.Editable = state.CanEdit;
        DefaultSetButton.SetDisabled(!state.CanEdit, Loc.GetString("taxation-console-denied-tooltip"));

        RefreshRows();
    }

    private void RefreshRows()
    {
        if (_state == null)
            return;

        _visible.Clear();
        _visible.AddRange(_state.Goods.Where(g => g.Name.MatchesFilter(FilterEdit.Text)));

        _rows.Sync(_visible, good => good.ProtoId, (row, good) => row.Update(good, _canEdit));

        EmptyLabel.Visible = _visible.Count == 0;
        EmptyLabel.Text = Loc.GetString(_state.Goods.Count == 0
            ? "taxation-console-no-goods"
            : "taxation-console-no-matches");
    }

    /// <summary>
    ///     One good's row. Built once per good and updated in place, so the rate box keeps whatever the
    ///     operator typed across the console's three-second refresh.
    /// </summary>
    private sealed class GoodRow : PanelContainer
    {
        private readonly TaxationConsoleWindow _owner;

        private readonly Label _name;
        private readonly Label _price;
        private readonly ConsoleValueEdit _rate;
        private readonly Button _set;
        private readonly Button _clear;

        private string _protoId = string.Empty;

        public GoodRow(TaxationConsoleWindow owner)
        {
            _owner = owner;

            _name = new Label
            {
                StyleClasses = { "ConsoleText" },
                HorizontalExpand = true,
                ClipText = true,
            };

            _price = new Label
            {
                StyleClasses = { "ConsoleText" },
                FontColorOverride = ConsolePalette.Muted,
                MinWidth = 110,
            };

            _rate = new ConsoleValueEdit
            {
                MinWidth = 70,
                Margin = new Thickness(4, 0, 2, 0),
            };
            _rate.OnTextEntered += _ => ApplyRate();

            _set = new Button { Text = Loc.GetString("taxation-console-set") };
            _set.OnPressed += _ => ApplyRate();

            _clear = new Button
            {
                Text = Loc.GetString("taxation-console-clear"),
                Margin = new Thickness(2, 0, 0, 0),
            };
            _clear.OnPressed += _ =>
            {
                // The override is being dropped, so the box is handed back to the console: whatever was
                // typed stops being pending and the next push shows the rate this good falls back to.
                _rate.ClearEdited();
                _owner.OnClearOverride?.Invoke(_protoId);
            };

            var inner = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(6, 3),
                HorizontalExpand = true,
                SeparationOverride = 4,
            };

            inner.AddChild(_name);
            inner.AddChild(_price);
            inner.AddChild(new Label { Text = "%", StyleClasses = { "ConsoleText" }, VerticalAlignment = VAlignment.Center });
            inner.AddChild(_rate);
            inner.AddChild(_set);
            inner.AddChild(_clear);

            AddChild(inner);
        }

        /// <summary>Sends this good's override. Anything that is not a rate is left where it was typed.</summary>
        private void ApplyRate()
        {
            if (!_owner.TryParsePercent(_rate.Text, out var rate))
                return;

            _rate.SetSubmitted(ToPercentString(rate));
            _owner.OnSetOverride?.Invoke((_protoId, rate));
        }

        public void Update(TaxableGoodEntry good, bool canEdit)
        {
            _protoId = good.ProtoId;

            _name.SetTextIfChanged(good.Name);
            _price.SetTextIfChanged(Loc.GetString("taxation-console-good-price", ("price", good.BasePrice)));

            _rate.SetValue(ToPercentString(good.EffectiveRate));
            _rate.Editable = canEdit;
            // A rate the operator set themselves is worth telling apart from one inherited from the default.
            _rate.IdleModulate = good.HasOverride ? ConsolePalette.Override : null;

            _set.SetDisabled(!canEdit, Loc.GetString("taxation-console-denied-tooltip"));
            _clear.SetDisabled(!canEdit || !good.HasOverride, Loc.GetString(canEdit
                ? "taxation-console-no-override-tooltip"
                : "taxation-console-denied-tooltip"));
        }
    }

    private static string ToPercentString(float fraction)
    {
        return Math.Round(fraction * 100f).ToString(CultureInfo.InvariantCulture);
    }

    /// <summary>Parses a percent string (e.g. "25") into a fraction (0.25). Returns false if invalid.</summary>
    private bool TryParsePercent(string? text, out float fraction)
    {
        fraction = 0f;
        if (string.IsNullOrWhiteSpace(text))
            return false;

        if (!float.TryParse(text.Trim().TrimEnd('%'), NumberStyles.Float, CultureInfo.InvariantCulture, out var pct))
            return false;

        // float.TryParse accepts "NaN" and "Infinity" outright, and Math.Clamp passes NaN straight through
        // because every comparison against it is false. An operator typing NaN would otherwise store it as
        // the live rate, where it silently zeroes the station's cut and renders as "NaN" on the console.
        if (!float.IsFinite(pct))
            return false;

        // Clamp to what the server will actually accept, not a flat 100%, so an over-limit entry does not
        // get taken here and then bounce back to the ceiling on the next state push.
        //
        // The ceiling arrives off the wire straight from the prototype, so it is put through the same
        // 0..1 sanitisation the server applies before it is used. Math.Clamp throws outright when its
        // max is below its min, so an out-of-range maxTaxRate would take the Set button down with it.
        var max = _state?.MaxRate ?? 1f;
        max = float.IsFinite(max) ? Math.Clamp(max, 0f, 1f) : 1f;

        fraction = Math.Clamp(pct / 100f, 0f, max);
        return true;
    }
}
