using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared._Crescent.Taxation;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Crescent.Taxation;

[GenerateTypedNameReferences]
public sealed partial class TreasuryConsoleWindow : FancyWindow
{
    /// <summary>Raised with the amount of credits to withdraw.</summary>
    public event Action<int>? OnWithdraw;

    /// <summary>Eclipsion - raised with a pending purchase's id and whether it was approved.</summary>
    public event Action<uint, bool>? OnPurchaseDecision;

    private int _remaining;
    private bool _authorized;

    public TreasuryConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("treasury-console-title");

        WithdrawButton.OnPressed += _ =>
        {
            if (int.TryParse(AmountEdit.Text?.Trim(), NumberStyles.Integer, CultureInfo.InvariantCulture, out var amount) && amount > 0)
                OnWithdraw?.Invoke(amount);
        };

        // Asks for the player's own remaining allowance, not the whole balance. Asking for the balance
        // got silently clamped to the cap, so the button reported a smaller figure than the one above
        // it with nothing to explain the gap.
        WithdrawAllButton.OnPressed += _ =>
        {
            if (_remaining > 0)
                OnWithdraw?.Invoke(_remaining);
        };
    }

    public void UpdateState(TreasuryConsoleState state)
    {
        _remaining = state.Remaining;
        _authorized = state.Authorized;

        BalanceLabel.Text = Loc.GetString("treasury-console-balance", ("balance", state.Balance));

        RemainingLabel.Text = Loc.GetString("treasury-console-remaining",
            ("remaining", state.Remaining), ("percent", state.CapPercent));
        RemainingLabel.Modulate = state.Remaining > 0 ? Color.LightGray : Color.DarkOrange;

        if (state.AlarmActive)
        {
            AlarmLabel.Text = Loc.GetString("treasury-console-alarm");
            AlarmLabel.Modulate = Color.Red;
        }
        else
        {
            AlarmLabel.Text = string.Empty;
        }

        StatusLabel.Text = Loc.GetString(state.Authorized
            ? "treasury-console-authorized"
            : "treasury-console-unauthorized");
        StatusLabel.Modulate = state.Authorized ? Color.LightGreen : Color.OrangeRed;

        AmountEdit.Editable = state.Authorized;
        WithdrawButton.Disabled = !state.Authorized;
        WithdrawAllButton.Disabled = !state.Authorized;

        UpdateRequests(state.Requests); // Eclipsion - purchase approval
    }

    // Eclipsion Start - purchase approval
    /// <summary>
    /// Rebuilds the pending purchase list. An approved request stays on the list until the buyer
    /// actually collects the ship, so the people who signed it off can see what is still outstanding
    /// against the balance above.
    /// </summary>
    private void UpdateRequests(List<TreasuryPurchaseRequestState> requests)
    {
        RequestsContainer.RemoveAllChildren();

        if (requests.Count == 0)
        {
            RequestsContainer.AddChild(new Label
            {
                Text = Loc.GetString("treasury-console-requests-empty"),
                Modulate = Color.DarkGray,
            });
            return;
        }

        foreach (var request in requests)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 8),
            };

            row.AddChild(new Label
            {
                Text = Loc.GetString("treasury-console-request-line",
                    ("buyer", request.Buyer), ("vessel", request.Vessel), ("price", request.Price)),
                ClipText = false,
            });

            if (request.Approved)
            {
                row.AddChild(new Label
                {
                    Text = Loc.GetString("treasury-console-request-approved", ("approver", request.Approver ?? string.Empty)),
                    Modulate = Color.LightGreen,
                });
            }

            var buttons = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            var id = request.Id;

            // An already-approved request keeps its Deny button: sign-off can be withdrawn right up
            // until the buyer collects, which is the only way to stop one once it has been given.
            if (!request.Approved)
            {
                var approve = new Button
                {
                    Text = Loc.GetString("treasury-console-request-approve"),
                    Disabled = !_authorized,
                };
                approve.OnPressed += _ => OnPurchaseDecision?.Invoke(id, true);
                buttons.AddChild(approve);
            }

            var deny = new Button
            {
                Text = Loc.GetString("treasury-console-request-deny"),
                Disabled = !_authorized,
                Margin = new Thickness(6, 0, 0, 0),
            };
            deny.OnPressed += _ => OnPurchaseDecision?.Invoke(id, false);
            buttons.AddChild(deny);

            row.AddChild(buttons);
            RequestsContainer.AddChild(row);
        }
    }
    // Eclipsion End
}
