using System.Linq;
using Content.Client._Crescent.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Crescent.Payment;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Timing;

namespace Content.Client._Crescent.Payment;

[GenerateTypedNameReferences]
public sealed partial class PaymentPanel : BoxContainer
{
    private static readonly Color RowBg = Color.FromHex("#1C1C22");
    private static readonly Color StaleBg = Color.FromHex("#2A2118");

    public event Action<NetUserId, int>? OnSetSalary;
    public event Action<NetUserId>? OnClearSalary;
    public event Action<NetUserId, int, string>? OnBonus;

    private readonly ConsoleRowList<NetUserId, MemberRow> _rows;
    private readonly List<PaymentMemberEntry> _visible = new();

    private PaymentBonusDialog? _bonusDialog;
    private PaymentConsoleState? _state;
    private bool _rowsDirty;

    public PaymentPanel()
    {
        RobustXamlLoader.Load(this);

        _rows = new ConsoleRowList<NetUserId, MemberRow>(MembersContainer, () => new MemberRow(this));

        FilterEdit.OnTextChanged += _ => RefreshRows();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        // The dialog is its own window, so nothing else ties it to this panel's lifetime. Without
        // this it survives the console closing and fires its callback into a disposed BUI.
        if (disposing)
            CloseBonusDialog();
    }

    private void CloseBonusDialog()
    {
        _bonusDialog?.Close();
        _bonusDialog = null;
    }

    public void UpdateState(PaymentConsoleState state)
    {
        _state = state;

        TreasuryLabel.SetTextIfChanged(state.TreasuryBound
            ? Loc.GetString("payment-console-treasury-value", ("amount", state.Treasury))
            : Loc.GetString("payment-console-treasury-unbound"));
        TreasuryLabel.FontColorOverride = state.TreasuryBound ? ConsolePalette.Good : ConsolePalette.Warn;

        // Total committed spend, so command can see the burn rate against the balance above.
        var perHour = state.Members.Sum(m => m.SalaryPerHour);
        var overBudget = state.TreasuryBound && perHour > state.Treasury;

        PayrollLabel.SetTextIfChanged(Loc.GetString("payment-console-payroll-total", ("amount", perHour)));
        PayrollLabel.FontColorOverride = overBudget ? ConsolePalette.Warn : ConsolePalette.Muted;
        PayrollLabel.ToolTip = overBudget ? Loc.GetString("payment-console-payroll-over-tooltip") : null;

        RefreshRows();
    }

    /// <summary>
    ///     On a mainframe every console's panel stays open at once and only the selected tab is visible. A
    ///     hidden tab rebuilding its roster every three seconds costs the shared window a relayout for a list
    ///     nobody is looking at, so the work is deferred until the tab is actually on screen. FrameUpdate is
    ///     not called on an invisible control, which is exactly the signal we want.
    /// </summary>
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_rowsDirty)
            RefreshRows();
    }

    private void RefreshRows()
    {
        if (_state == null)
            return;

        // Deferred until this tab is the one being shown.
        if (!VisibleInTree)
        {
            _rowsDirty = true;
            return;
        }

        _rowsDirty = false;

        // Name or job, so command can pull up "everyone in security" as easily as one person.
        _visible.Clear();
        _visible.AddRange(_state.Members.Where(m =>
            m.Name.MatchesFilter(FilterEdit.Text) || m.Job.MatchesFilter(FilterEdit.Text)));

        _rows.Sync(_visible, member => member.User, (row, member) => row.Update(member));

        EmptyLabel.Visible = _visible.Count == 0;
        EmptyLabel.Text = Loc.GetString(_state.Members.Count == 0
            ? "payment-console-no-members"
            : "payment-console-no-matches");
    }

    /// <summary>
    ///     One crew member's payroll row. Built once and updated in place, so the salary box survives the
    ///     console's three-second refresh while somebody is typing a figure into it.
    /// </summary>
    private sealed class MemberRow : PanelContainer
    {
        private readonly PaymentPanel _owner;
        private readonly StyleBoxFlat _background;

        private readonly Label _name;
        private readonly Label _job;
        private readonly Label _status;
        private readonly ConsoleValueEdit _salary;
        private readonly MonotoneButton _set;
        private readonly MonotoneButton _clear;
        private readonly MonotoneButton _bonus;

        private PaymentMemberEntry _member;

        public MemberRow(PaymentPanel owner)
        {
            _owner = owner;

            MinHeight = 32;
            _background = new StyleBoxFlat { BackgroundColor = RowBg };
            PanelOverride = _background;

            _name = new Label
            {
                StyleClasses = { "ConsoleText" },
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 2f,
                ClipText = true,
            };

            _job = new Label
            {
                StyleClasses = { "ConsoleText" },
                FontColorOverride = ConsolePalette.Muted,
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1.5f,
                ClipText = true,
            };

            _status = new Label
            {
                StyleClasses = { "ConsoleText" },
                MinWidth = 90,
            };

            _salary = new ConsoleValueEdit
            {
                MinWidth = 90,
                PlaceHolder = Loc.GetString("payment-console-salary-placeholder"),
            };

            // Enter applies the figure. Without it the box swallowed the key and the typed salary sat
            // there unsent until the operator noticed it had never taken.
            _salary.OnTextEntered += _ => ApplySalary();

            // Joined into one control strip so the three actions read as a single unit per member.
            _set = new MonotoneButton
            {
                Text = Loc.GetString("payment-console-set-button"),
                Shape = MonotoneButtonShape.OpenRight,
                MinWidth = 70,
            };
            _set.OnPressed += _ => ApplySalary();

            _clear = new MonotoneButton
            {
                Text = Loc.GetString("payment-console-clear-button"),
                Shape = MonotoneButtonShape.OpenBoth,
                MinWidth = 70,
            };
            _clear.OnPressed += _ =>
            {
                // Drops whatever was typed as well: the operator asked for no salary, so a pending
                // figure in the box is not something to keep holding onto.
                _salary.SetSubmitted("0");
                _owner.OnClearSalary?.Invoke(_member.User);
            };

            _bonus = new MonotoneButton
            {
                Text = Loc.GetString("payment-console-bonus-button"),
                Shape = MonotoneButtonShape.OpenLeft,
                MinWidth = 70,
            };
            _bonus.OnPressed += _ => _owner.OpenBonusDialog(_member);

            var inner = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                Margin = new Thickness(6, 4),
                HorizontalExpand = true,
                SeparationOverride = 4,
            };

            inner.AddChild(_name);
            inner.AddChild(_job);
            inner.AddChild(_status);
            inner.AddChild(_salary);
            inner.AddChild(_set);
            inner.AddChild(_clear);
            inner.AddChild(_bonus);

            AddChild(inner);
        }

        /// <summary>
        ///     Sends whatever is in the salary box and puts the box back in step with what was sent.
        /// </summary>
        /// <remarks>
        ///     Something that is not a number is left exactly where the operator typed it, still tinted as
        ///     pending. Overwriting it with the standing salary would land them right back in the bug this
        ///     console was reported for - type a figure, watch it turn into 0 - only this time deserved.
        /// </remarks>
        private void ApplySalary()
        {
            if (!int.TryParse(_salary.Text, out var salary) || salary < 0)
                return;

            // Mirror the server-side cap here so an over-limit entry snaps back visibly instead of
            // being silently trimmed after the round-trip.
            salary = Math.Min(salary, PaymentConsole.MaxSalaryPerHour);
            _salary.SetSubmitted(salary.ToString());

            _owner.OnSetSalary?.Invoke(_member.User, salary);
        }

        public void Update(PaymentMemberEntry member)
        {
            _member = member;

            _background.BackgroundColor = member.Stale ? StaleBg : RowBg;

            _name.SetTextIfChanged(member.Name);
            // Greyed out when they're on the payroll but no longer in the faction, so command can prune.
            _name.FontColorOverride = member.Stale ? ConsolePalette.Muted : ConsolePalette.Normal;

            _job.SetTextIfChanged(member.Job);

            _status.SetTextIfChanged(member.Stale
                ? Loc.GetString("payment-console-status-stale")
                : member.Payable
                    ? Loc.GetString("payment-console-status-payable")
                    : Loc.GetString("payment-console-status-unpayable"));
            _status.FontColorOverride = member.Payable ? ConsolePalette.Good : ConsolePalette.Warn;
            _status.ToolTip = member.Stale
                ? Loc.GetString("payment-console-status-stale-tooltip")
                : member.Payable
                    ? null
                    : Loc.GetString("payment-console-status-unpayable-tooltip");

            _salary.SetValue(member.SalaryPerHour.ToString());

            // Also the way out of a pending edit: with no salary set there is nothing else on the row
            // that drops a figure the operator has thought better of.
            _clear.SetDisabled(member.SalaryPerHour <= 0 && !_salary.Edited,
                Loc.GetString("payment-console-no-salary-tooltip"));
            _bonus.SetDisabled(!member.Payable, Loc.GetString("payment-console-not-payable-tooltip"));
        }
    }

    private void OpenBonusDialog(PaymentMemberEntry member)
    {
        // Only one at a time, so an earlier dialog can't be left behind pointing at another member.
        CloseBonusDialog();

        var dialog = new PaymentBonusDialog(member.Name);
        var user = member.User;

        dialog.OnConfirmed += (amount, reason) => OnBonus?.Invoke(user, amount, reason);
        dialog.OnClose += () =>
        {
            if (_bonusDialog == dialog)
                _bonusDialog = null;
        };

        _bonusDialog = dialog;
        dialog.OpenCentered();
    }
}
