- type: job
  id: OperativeTFSC
  name: job-name-operative
  description: job-description-operative
  playTimeTracker: JobOperativeTFSC
  ranks:
    RatRankTFSCOperativeLead:
    - !type:CharacterPlaytimeRequirement
      tracker: JobOperativeTFSC
      min: 108000 # 30 hours
    RatRankTFSCOperativeSenior:
    - !type:CharacterPlaytimeRequirement
      tracker: JobOperativeTFSC
      min: 72000 # 20 hours
    RatRankTFSCOperativeMiddle:
    - !type:CharacterPlaytimeRequirement
      tracker: JobOperativeTFSC
      min: 36000 # 10 hours
    RatRankTFSCOperativeJunior: []
  weight: 4
  startingGear: OperativeGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconSyndieOperative"
  chatNameColor: "#264180"
  supervisors: You answer to the Cyberdawn Supervisor and to valid Administrator decisions on Federation-wide matters.
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
        - Skeleton # Restricted to selected TFSC roles, including Gorlex Infanteer.
    - !type:CharacterOverallTimeRequirement
      min: 0
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: NukeOperative
      - type: HullrotFaction
        faction: TFSC
      - type: LanguageAdder
        addSpoken:
          - Freespeak
          - SolCommon
        addUnderstood:
          - Freespeak
          - SolCommon
  access:
  - Command
  - Maintenance
  # Shared TFCF gameplay keyring; company access still marks Cyberdawn's internal facilities.
  - SyndicateBasic
  - SyndicateGorlex
  - SyndicateInterdyne
  - SyndicateSaws
  - SyndicateRamzi
  - Engineering
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: OperativeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateSoldierCyberdawn
    shoes: ClothingShoesBootsCombat
    id: OperativePDA
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterArmorKendoBogu
    ears: ClothingHeadsetTFSCCyberdawn
    back: ClothingBackpackTFSC
    pocket1: WeaponPistolAnsem
    belt: ClothingBeltSyndicateWebbing
  storage:
    belt:
      - Flash
      - Tourniquet
      - MagazinePistolHeavy
      - CombatKnife
      - Zipties
