using Content.Client.GameTicking.Managers;
using Content.Shared.Roles;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;

namespace Content.Client._NF.Latejoin;

[GenerateTypedNameReferences]
public sealed partial class NewFrontierLateJoinJobButton : Button
{
    private readonly IPrototypeManager _prototypeManager;
    private readonly ClientGameTicker _gameTicker;
    private readonly NetEntity _station;
    private readonly string _jobId;

    private bool _locked;

    /// <summary>
    /// The player may not take this role at all - whitelist, character requirements or a faction cap.
    /// Tracked apart from <see cref="Button.Disabled"/> so a slot-count refresh cannot re-enable it.
    /// </summary>
    public bool Locked
    {
        get => _locked;
        set
        {
            _locked = value;
            if (value)
                Disabled = true;
        }
    }

    public NewFrontierLateJoinJobButton(NetEntity station, string jobId, ClientGameTicker gameTicker, IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);
        _prototypeManager = prototypeManager;
        _gameTicker = gameTicker;
        _station = station;
        _jobId = jobId;

        _gameTicker.LobbyJobsAvailableUpdated += UpdateButton;
        UpdateButton(_gameTicker.JobsAvailable);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
            _gameTicker.LobbyJobsAvailableUpdated -= UpdateButton;
    }

    private void UpdateButton(IReadOnlyDictionary<NetEntity, Dictionary<string, uint?>> obj)
    {
        // An event already being dispatched keeps calling handlers that unsubscribed part-way through it,
        // so a button the window replaced during this very update can still land here.
        if (Disposed)
            return;

        if (!obj.TryGetValue(_station, out var stationJobs) || !stationJobs.TryGetValue(_jobId, out var slots))
        {
            Visible = false;
            return;
        }

        // TryIndex: the station can advertise a job this client has no prototype for.
        if (!_prototypeManager.TryIndex<JobPrototype>(_jobId, out var prototype))
        {
            Visible = false;
            return;
        }

        Visible = true;

        if (_prototypeManager.TryIndex(prototype.Icon, out var jobIcon))
            JobIcon.Texture = jobIcon.Icon.Frame0();

        JobText.Text = $"{prototype.LocalizedName} ({slots?.ToString() ?? Loc.GetString("late-join-unlimited")})";

        Disabled = _locked || slots == 0;
    }
}
