using Content.Client.CrewManifest;
using Content.Client.GameTicking.Managers;
using Content.Client.Lobby;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.UserInterface.Controls;
using Content.Client._Crescent.Factions;
using Content.Shared.Customization.Systems;
using Content.Shared.Players.PlayTimeTracking;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Console;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Timer = Robust.Shared.Timing.Timer;

namespace Content.Client._NF.Latejoin;

[GenerateTypedNameReferences]
public sealed partial class NFLateJoinGui : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IConsoleHost _consoleHost = default!;
    [Dependency] private readonly JobRequirementsManager _playManager = default!;
    [Dependency] private readonly IClientPreferencesManager _prefs = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IConfigurationManager _configManager = default!;

    private ClientGameTicker _gameTicker;
    private CharacterRequirementsSystem _characterRequirements;
    private FactionBalanceSystem _factionBalance;

    private NetEntity _lastSelection;

    private readonly Dictionary<string, NewFrontierLateJoinJobButton> _buttons = new();

    public NFLateJoinGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _gameTicker = EntitySystem.Get<ClientGameTicker>();
        _gameTicker.LobbyJobsAvailableUpdated += UpdateUi;
        _characterRequirements = EntitySystem.Get<CharacterRequirementsSystem>();
        _factionBalance = EntitySystem.Get<FactionBalanceSystem>();
        _factionBalance.Updated += OnFactionBalanceUpdated;
        VesselSelection.VesselItemList.OnItemSelected += args =>
        {
            UpdateUi(_gameTicker.JobsAvailable);
        };
        CrewManifestButton.OnPressed += _ =>
        {
            EntitySystem.Get<CrewManifestSystem>().RequestCrewManifest(_lastSelection);
        };

        _lastSelection = _gameTicker.JobsAvailable.Keys.FirstOrNull() ?? NetEntity.Invalid;

        _prefs.SlotSelected += OnSlotSelected;

        // Closing a window only orphans it, so without this the window - and every job button in it - stays
        // subscribed to the ticker and keeps rebuilding itself for the rest of the session. Deferred by a tick
        // on purpose: Close() is raised from inside a job button's own OnPressed, and tearing the button tree
        // down there leaves BaseButton.KeyBindUp running against a control that no longer exists.
        OnClose += () => Timer.Spawn(0, () =>
        {
            if (!Disposed)
                Dispose();
        });

        UpdateUi(_gameTicker.JobsAvailable);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing)
            return;

        _gameTicker.LobbyJobsAvailableUpdated -= UpdateUi;
        _factionBalance.Updated -= OnFactionBalanceUpdated;
        // This one used to be a lambda that was never unsubscribed, so a closed window kept rebuilding
        // its job list every time the player switched character slot in the lobby.
        _prefs.SlotSelected -= OnSlotSelected;
    }

    private void OnSlotSelected(int slot)
    {
        UpdateUi(_gameTicker.JobsAvailable);
    }

    private void OnFactionBalanceUpdated()
    {
        UpdateUi(_gameTicker.JobsAvailable);
    }

    public void UpdateUi(IReadOnlyDictionary<NetEntity, Dictionary<string, uint?>> obj)
    {
        if (VesselSelection.Selected is null)
        {
            CrewManifestButton.Visible = false;
            // No vessel means no roles; leaving the old list up would offer jobs on a ship that is gone.
            JobList.DisposeAllChildren();
            _buttons.Clear();
            return;
        }

        CrewManifestButton.Visible = true;

        var station = VesselSelection.Selected.Value;
        // The selected vessel can be gone from a fresh snapshot (destroyed, or the list rebuilt under us),
        // and indexing it would take the whole window down.
        if (!obj.TryGetValue(station, out var jobs))
        {
            JobList.DisposeAllChildren();
            _buttons.Clear();
            return;
        }

        // Dispose, don't just orphan: every button subscribes to LobbyJobsAvailableUpdated, so removed
        // ones stayed subscribed and piled up for as long as the window was open.
        JobList.DisposeAllChildren();
        _buttons.Clear();

        _lastSelection = station;

        foreach (var (departmentName, departmentJobs) in GroupJobsByDepartment(jobs))
        {
            if (departmentName != null)
            {
                JobList.AddChild(new Label
                {
                    Text = Loc.GetString("late-join-gui-department-jobs-label", ("departmentName", departmentName)),
                    StyleClasses = { "LabelBig" },
                    Margin = new Thickness(0, 6, 0, 0),
                });
            }

            foreach (var job in departmentJobs)
                AddJobButton(station, job);
        }
    }

    /// <summary>
    /// Orders the station's open roles the same way the character editor does - department by department,
    /// each sorted by display weight - instead of leaving them in the arbitrary order the dictionary
    /// happens to enumerate in. Roles in no department are listed last.
    /// </summary>
    private List<(string? DepartmentName, List<JobPrototype> Jobs)> GroupJobsByDepartment(Dictionary<string, uint?> jobs)
    {
        var groups = new List<(string?, List<JobPrototype>)>();
        var placed = new HashSet<string>();

        var departments = _prototypeManager.EnumeratePrototypes<DepartmentPrototype>().ToArray();
        Array.Sort(departments, DepartmentUIComparer.Instance);

        foreach (var department in departments)
        {
            var departmentJobs = new List<JobPrototype>();
            foreach (var jobId in department.Roles)
            {
                // A role can sit in more than one department; show it under the first one only.
                if (!jobs.ContainsKey(jobId) || placed.Contains(jobId))
                    continue;

                // TryIndex: the station may advertise a job this client's prototypes do not have.
                if (!_prototypeManager.TryIndex<JobPrototype>(jobId, out var job))
                    continue;

                placed.Add(jobId);
                departmentJobs.Add(job);
            }

            if (departmentJobs.Count == 0)
                continue;

            departmentJobs.Sort(JobUIComparer.Instance);
            groups.Add((Loc.GetString($"department-{department.ID}"), departmentJobs));
        }

        var orphans = new List<JobPrototype>();
        foreach (var jobId in jobs.Keys)
        {
            if (placed.Contains(jobId))
                continue;

            if (_prototypeManager.TryIndex<JobPrototype>(jobId, out var job))
                orphans.Add(job);
        }

        if (orphans.Count > 0)
        {
            orphans.Sort(JobUIComparer.Instance);
            groups.Add((null, orphans));
        }

        return groups;
    }

    private void AddJobButton(NetEntity station, JobPrototype job)
    {
        var jobId = job.ID;
        if (_buttons.ContainsKey(jobId))
            return;

        var newButton = new NewFrontierLateJoinJobButton(station, jobId, _gameTicker, _prototypeManager);
        newButton.OnPressed += args =>
        {
            Logger.InfoS("latejoin", $"Late joining as ID: {jobId}");
            _consoleHost.ExecuteCommand($"joingame {CommandParsing.Escape(jobId)} {station}");
            Close();
        };

        if (!_playManager.CheckJobWhitelist(job, out var denyReason))
        {
            newButton.Locked = true;
            SetTooltip(newButton, denyReason);
        }

        if (!_characterRequirements.CheckRequirementsValid(job.Requirements ?? new(),
            job,
            (HumanoidCharacterProfile) (_prefs.Preferences?.SelectedCharacter
                ?? HumanoidCharacterProfile.DefaultWithSpecies()),
            _playManager.GetRawPlayTimeTrackers(),
            _playManager.IsWhitelisted(),
            job,
            _entityManager,
            _prototypeManager,
            _configManager,
            out var reasons))
        {
            newButton.Locked = true;
            if (reasons.Count > 0)
                SetTooltip(newButton, _characterRequirements.GetRequirementsText(reasons));
        }

        // Population-scaled join caps. The server refuses this anyway, so lock the button and say why
        // rather than letting the player press it and quietly get nothing.
        if (_factionBalance.IsJobBlocked(jobId, out var fullFaction, out var balance))
        {
            newButton.Locked = true;
            // A supplier set above wins over ToolTip, and the cap is the reason that will actually clear.
            newButton.TooltipSupplier = null;
            newButton.ToolTip = Loc.GetString(balance.Defeated
                    ? "faction-defeated-job-locked"
                    : "faction-balance-job-locked",
                ("faction", _prototypeManager.TryIndex<FactionPrototype>(fullFaction, out var factionProto)
                    ? factionProto.Name
                    : fullFaction),
                ("count", balance.Count),
                ("cap", balance.Cap));
        }

        JobList.AddChild(newButton);

        _buttons.Add(jobId, newButton);
    }

    /// <summary>
    /// FormattedMessage.ToString() hands back the raw markup, tags and all. Feed the message to a real
    /// tooltip instead so the player reads the reason rather than "[color=yellow]...".
    /// </summary>
    private static void SetTooltip(Control control, FormattedMessage message)
    {
        var tooltip = new Tooltip();
        tooltip.SetMessage(message);
        control.TooltipSupplier = _ => tooltip;
    }
}
