using System.Linq;
using Content.Client.GameTicking.Managers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;

namespace Content.Client._NF.Latejoin;

[GenerateTypedNameReferences]
public sealed partial class VesselListControl : BoxContainer
{

    private ClientGameTicker _gameTicker;

    public Comparison<NetEntity>? Comparison;

    public NetEntity? Selected
    {
        get
        {
            var i = VesselItemList.GetSelected().FirstOrDefault();
            if (i is null)
                return null;

            return (NetEntity) i.Metadata!;
        }
    }

    private IReadOnlyDictionary<NetEntity, Dictionary<string, uint?>>? _lastJobState;

    public VesselListControl()
    {
        _gameTicker = EntitySystem.Get<ClientGameTicker>();
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _gameTicker.LobbyJobsAvailableUpdated += UpdateUi;
        Comparison = DefaultComparison;

        UpdateUi(_gameTicker.JobsAvailable);

        FilterLineEdit.OnTextChanged += _ =>
        {
            if (_lastJobState != null)
                UpdateUi(_lastJobState);
        };
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _gameTicker.LobbyJobsAvailableUpdated -= UpdateUi;
    }

    private static readonly Dictionary<string, uint?> EmptyJobs = new();

    /// <summary>
    /// Open roles on a station, or an empty set if its job list has not arrived yet. Indexing straight
    /// into <see cref="ClientGameTicker.JobsAvailable"/> throws while the two dictionaries are out of step.
    /// </summary>
    private IReadOnlyDictionary<string, uint?> JobsOn(NetEntity station)
    {
        return _gameTicker.JobsAvailable.TryGetValue(station, out var jobs)
            ? jobs
            : EmptyJobs;
    }

    private string NameOf(NetEntity station)
    {
        return _gameTicker.StationNames.TryGetValue(station, out var name) ? name : string.Empty;
    }

    private int DefaultComparison(NetEntity x, NetEntity y)
    {
        var xJobs = JobsOn(x);
        var yJobs = JobsOn(y);

        var xContainsSR = xJobs.ContainsKey("StationRepresentative");
        var yContainsSR = yJobs.ContainsKey("StationRepresentative");

        var xContainsSheriff = xJobs.ContainsKey("Sheriff");
        var yContainsSheriff = yJobs.ContainsKey("Sheriff");

        var xContainsPirateCaptain = xJobs.ContainsKey("PirateCaptain");
        var yContainsPirateCaptain = yJobs.ContainsKey("PirateCaptain");

        // Prioritize "StationRepresentative"
        switch (xContainsSR)
        {
            case true when !yContainsSR:
                return -1;
            case false when yContainsSR:
                return 1;
        }

        // If both or neither contain "StationRepresentative", prioritize "Sheriff"
        switch (xContainsSheriff)
        {
            case true when !yContainsSheriff:
                return -1;
            case false when yContainsSheriff:
                return 1;
        }

        // If both or neither contain "StationRepresentative", "Sheriff" prioritize "PirateCaptain"
        switch (xContainsPirateCaptain)
        {
            case true when !yContainsPirateCaptain:
                return -1;
            case false when yContainsPirateCaptain:
                return 1;
        }

        // If both or neither contain "StationRepresentative" and "Sheriff", sort by jobCountComparison
        var jobCountComparison = -(int) (xJobs.Values.Sum(a => a ?? 0) -
                                         yJobs.Values.Sum(b => b ?? 0));
        var nameComparison = string.Compare(NameOf(x), NameOf(y), StringComparison.Ordinal);

        // Combine the comparisons
        return jobCountComparison != 0 ? jobCountComparison : nameComparison;
    }

    private void Sort()
    {
        if (Comparison != null)
            VesselItemList.Sort((a, b) => Comparison((NetEntity) a.Metadata!, (NetEntity) b.Metadata!));
    }

    private void UpdateUi(IReadOnlyDictionary<NetEntity, Dictionary<string, uint?>> obj)
    {
        // Clearing the list drops the selection, and every slot change on any ship pushes an update here.
        // Without this the player gets bounced back to the top of the list mid-browse.
        var previous = Selected;

        VesselItemList.Clear();

        var filter = FilterLineEdit.Text.Trim();

        foreach (var (key, name) in _gameTicker.StationNames)
        {
            if (!string.IsNullOrEmpty(filter) &&
                !name.Contains(filter, StringComparison.InvariantCultureIgnoreCase))
            {
                continue;
            }

            // A station can be named before its job list arrives; show it as empty rather than throwing.
            var jobsAvailable = _gameTicker.JobsAvailable.TryGetValue(key, out var stationJobs)
                ? stationJobs.Values.Sum(a => a ?? 0)
                : 0;

            VesselItemList.Add(new ItemList.Item(VesselItemList)
            {
                Metadata = key,
                Text = name + $" ({jobsAvailable})"
            });
        }

        _lastJobState = obj;
        Sort();

        if (VesselItemList.Count == 0)
            return;

        var restored = previous != null
            ? VesselItemList.FirstOrDefault(x => (NetEntity) x.Metadata! == previous.Value)
            : null;

        (restored ?? VesselItemList.First()).Selected = true;
    }
}
