using System.Collections.Generic;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI;

/// <summary>
///     One neighbouring character in the lobby carousel. A null <paramref name="Dummy"/> still gets an arrow but
///     no faded doll, which is what the left side does when there are only two characters to cycle between.
/// </summary>
public readonly record struct LobbyPreviewNeighbour(int Slot, EntityUid? Dummy, string Name);

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    private static readonly Vector2 MainSize = new(112f, 112f);
    private static readonly Vector2 GhostSize = new(76f, 76f);

    /// How far to either side of the selected character the neighbours sit. Small enough that they tuck behind it.
    private const float GhostOffset = 58f;

    private static readonly Color GhostModulate = Color.White.WithAlpha(0.35f);
    private static readonly Color GhostHoverModulate = Color.White.WithAlpha(0.7f);

    public Button CharacterSetupButton => CharacterSetup;

    /// <summary>
    ///     Raised with the preference slot the player picked with an arrow or by clicking a faded neighbour.
    /// </summary>
    public event Action<int>? CharacterSelected;

    private readonly List<EntityUid> _previewDummies = new();

    private int? _previousSlot;
    private int? _nextSlot;

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PreviousButton.OnPressed += _ =>
        {
            if (_previousSlot != null)
                CharacterSelected?.Invoke(_previousSlot.Value);
        };

        NextButton.OnPressed += _ =>
        {
            if (_nextSlot != null)
                CharacterSelected?.Invoke(_nextSlot.Value);
        };
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;
    }

    public void SetSummaryText(string value)
    {
        Summary.Text = value;
    }

    public void SetSprite(EntityUid uid)
    {
        SetCharacters(uid, null, null);
    }

    /// <summary>
    ///     Shows <paramref name="main"/> front and centre with the neighbouring characters faded out behind it.
    /// </summary>
    public void SetCharacters(EntityUid main, LobbyPreviewNeighbour? previous, LobbyPreviewNeighbour? next)
    {
        ClearDummies();

        _previousSlot = previous?.Slot;
        _nextSlot = next?.Slot;

        _previewDummies.Add(main);

        if (previous?.Dummy != null)
            _previewDummies.Add(previous.Value.Dummy.Value);

        if (next?.Dummy != null)
            _previewDummies.Add(next.Value.Dummy.Value);

        ViewBox.DisposeAllChildren();

        // Ghosts go in first so the selected character draws on top of them.
        if (previous?.Dummy != null)
            AddGhost(previous.Value, -GhostOffset, "lobby-character-preview-panel-previous-character-tooltip");

        if (next?.Dummy != null)
            AddGhost(next.Value, GhostOffset, "lobby-character-preview-panel-next-character-tooltip");

        var spriteView = new SpriteView
        {
            OverrideDirection = Direction.South,
            Scale = new Vector2(4f, 4f),
            MaxSize = MainSize,
            Stretch = SpriteView.StretchMode.Fill,
        };
        spriteView.SetEntity(main);
        AddCentered(spriteView, MainSize, 0f);

        PreviousButton.Visible = _previousSlot != null;
        NextButton.Visible = _nextSlot != null;

        if (_previousSlot != null)
            PreviousButton.ToolTip = Loc.GetString("lobby-character-preview-panel-previous-character-tooltip",
                ("name", previous!.Value.Name));

        if (_nextSlot != null)
            NextButton.ToolTip = Loc.GetString("lobby-character-preview-panel-next-character-tooltip",
                ("name", next!.Value.Name));
    }

    private void AddGhost(LobbyPreviewNeighbour neighbour, float offsetX, string tooltip)
    {
        var spriteView = new SpriteView
        {
            OverrideDirection = Direction.South,
            Scale = new Vector2(2.7f, 2.7f),
            MaxSize = GhostSize,
            Stretch = SpriteView.StretchMode.Fill,
            ModulateSelfOverride = GhostModulate,
        };
        spriteView.SetEntity(neighbour.Dummy!.Value);

        // A button so the faded character can just be clicked, but with no chrome of its own.
        var button = new ContainerButton
        {
            StyleBoxOverride = new StyleBoxEmpty(),
            ToolTip = Loc.GetString(tooltip, ("name", neighbour.Name)),
        };
        button.AddChild(spriteView);
        button.OnPressed += _ => CharacterSelected?.Invoke(neighbour.Slot);

        // Without a stylebox there is nothing else to say the doll is clickable.
        button.OnMouseEntered += _ => spriteView.ModulateSelfOverride = GhostHoverModulate;
        button.OnMouseExited += _ => spriteView.ModulateSelfOverride = GhostModulate;

        AddCentered(button, GhostSize, offsetX);
    }

    /// <summary>
    ///     Places a control of the given size in the middle of the view box, shifted sideways by
    ///     <paramref name="offsetX"/>. Sizing it by hand keeps overlapping dolls from pushing each other around.
    /// </summary>
    private void AddCentered(Control control, Vector2 size, float offsetX)
    {
        ViewBox.AddChild(control);

        LayoutContainer.SetAnchorPreset(control, LayoutContainer.LayoutPreset.Center);
        LayoutContainer.SetGrowHorizontal(control, LayoutContainer.GrowDirection.Constrain);
        LayoutContainer.SetGrowVertical(control, LayoutContainer.GrowDirection.Constrain);
        LayoutContainer.SetMarginLeft(control, offsetX - size.X / 2f);
        LayoutContainer.SetMarginRight(control, offsetX + size.X / 2f);
        LayoutContainer.SetMarginTop(control, -size.Y / 2f);
        LayoutContainer.SetMarginBottom(control, size.Y / 2f);
    }

    private void ClearDummies()
    {
        foreach (var dummy in _previewDummies)
        {
            _entManager.DeleteEntity(dummy);
        }

        _previewDummies.Clear();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        ClearDummies();
    }
}
