using System.Linq;
using Content.Shared._Crescent.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;
using Robust.Shared.Network; // Eclipsion - blocking

namespace Content.Client._Crescent.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class MoneyTransferUiFragment : LayoutContainer
{
    private static readonly TimeSpan ToastDuration = TimeSpan.FromSeconds(3.5);

    private static readonly StyleBoxFlat ToastStyleError = new()
    {
        BackgroundColor = Color.FromHex("#3a1f22"),
        BorderThickness = new Thickness(2),
        BorderColor = Color.FromHex("#c84a50"),
        ContentMarginLeftOverride = 10,
        ContentMarginRightOverride = 10,
        ContentMarginTopOverride = 8,
        ContentMarginBottomOverride = 8,
    };

    private static readonly StyleBoxFlat ToastStyleSuccess = new()
    {
        BackgroundColor = Color.FromHex("#1f3327"),
        BorderThickness = new Thickness(2),
        BorderColor = Color.FromHex("#54a068"),
        ContentMarginLeftOverride = 10,
        ContentMarginRightOverride = 10,
        ContentMarginTopOverride = 8,
        ContentMarginBottomOverride = 8,
    };

    private int _toastGeneration;

    public event Action<NetEntity, int, string>? OnTransfer;

    /// <summary>Eclipsion - block/unblock a person: (target entity, account if known, block?).</summary>
    public event Action<NetEntity, NetUserId?, bool>? OnBlock;

    private NetEntity? _selectedRecipient;
    private readonly List<MoneyTransferRecipientState> _allRecipients = new();

    public MoneyTransferUiFragment()
    {
        RobustXamlLoader.Load(this);

        LayoutContainer.SetAnchorPreset(BackgroundPanel, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(MainColumn, LayoutContainer.LayoutPreset.Wide);
        // Transfer tab: form and toast share full tab rect; toast draws on top only on this tab.
        LayoutContainer.SetAnchorPreset(TransferFormColumn, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(ToastOverlay, LayoutContainer.LayoutPreset.Wide);
        ToastOverlay.MouseFilter = Robust.Client.UserInterface.Control.MouseFilterMode.Ignore;

        Tabs.SetTabTitle(0, Loc.GetString("money-transfer-ui-tab-transfer"));
        Tabs.SetTabTitle(1, Loc.GetString("money-transfer-ui-tab-history"));
        Tabs.SetTabTitle(2, Loc.GetString("money-transfer-ui-tab-blocked")); // Eclipsion - blocking

        SearchEdit.OnTextChanged += _ => ApplyRecipientFilter();

        RecipientList.OnItemSelected += args =>
        {
            if (args.ItemList[args.ItemIndex].Metadata is NetEntity ne)
                _selectedRecipient = ne;

            UpdateBlockButton(); // Eclipsion - blocking
        };

        // Eclipsion Start - blocking
        BlockButton.OnPressed += _ =>
        {
            if (_selectedRecipient is not { } target)
            {
                ShowToast(Loc.GetString("money-transfer-error-no-selection"), toastError: true);
                return;
            }

            OnBlock?.Invoke(target, null, !IsBlocked(target));
        };
        // Eclipsion End

        TransferButton.OnPressed += _ =>
        {
            if (_selectedRecipient is not { } target)
            {
                ShowToast(Loc.GetString("money-transfer-error-no-selection"), toastError: true);
                return;
            }

            if (!int.TryParse(AmountEdit.Text?.Trim(), out var amount) || amount <= 0)
            {
                ShowToast(Loc.GetString("money-transfer-error-amount"), toastError: true);
                return;
            }

            var comment = CommentEdit.Text ?? string.Empty;
            OnTransfer?.Invoke(target, amount, comment);
        };
    }

    public void UpdateState(MoneyTransferUiState state)
    {
        if (state.Error is { } err)
            ShowToast(err, toastError: true);
        else if (state.Success is { } ok)
            ShowToast(ok, toastError: false);

        _allRecipients.Clear();
        _allRecipients.AddRange(state.Recipients);
        ApplyRecipientFilter();
        UpdateBlockedList(state.Blocked); // Eclipsion - blocking

        HistoryContainer.RemoveAllChildren();
        if (state.History.Count == 0)
        {
            var empty = new Label { Text = Loc.GetString("money-transfer-ui-history-empty") };
            HistoryContainer.AddChild(empty);
        }
        else
        {
            foreach (var h in state.History)
            {
                var commentDisp = string.IsNullOrEmpty(h.Comment)
                    ? Loc.GetString("money-transfer-comment-none")
                    : h.Comment;
                var line = h.Outgoing
                    ? Loc.GetString("money-transfer-history-line-out",
                        ("time", h.TimeText),
                        ("to", h.Counterparty),
                        ("amount", h.Amount),
                        ("comment", commentDisp))
                    : Loc.GetString("money-transfer-history-line-in",
                        ("time", h.TimeText),
                        ("from", h.Counterparty),
                        ("amount", h.Amount),
                        ("comment", commentDisp));
                var label = new Label
                {
                    Text = line,
                    ClipText = false,
                };
                label.Margin = new Thickness(0, 0, 0, 4);
                HistoryContainer.AddChild(label);
            }
        }
    }

    // Eclipsion Start - blocking
    /// <summary>Whether the person currently picked in the send list is on the block list.</summary>
    private bool IsBlocked(NetEntity target)
    {
        return _allRecipients.Any(r => r.Entity == target && r.Blocked);
    }

    private void UpdateBlockButton()
    {
        var selected = _selectedRecipient;
        BlockButton.Disabled = selected == null;
        BlockButton.Text = Loc.GetString(selected is { } target && IsBlocked(target)
            ? "money-transfer-ui-unblock"
            : "money-transfer-ui-block");
    }

    /// <summary>
    ///     Rebuilds the block list tab. Entries come from the block list itself rather than from the send
    ///     list, so somebody who has logged out or died still has a row here to be unblocked from.
    /// </summary>
    private void UpdateBlockedList(List<MoneyTransferBlockedState> blocked)
    {
        BlockedContainer.RemoveAllChildren();

        if (blocked.Count == 0)
        {
            BlockedContainer.AddChild(new Label { Text = Loc.GetString("money-transfer-ui-blocked-empty") });
            return;
        }

        foreach (var entry in blocked)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 4),
            };

            row.AddChild(new Label
            {
                Text = entry.Name,
                HorizontalExpand = true,
                ClipText = true,
            });

            var button = new Button { Text = Loc.GetString("money-transfer-ui-unblock") };
            var user = entry.User;
            button.OnPressed += _ => OnBlock?.Invoke(NetEntity.Invalid, user, false);
            row.AddChild(button);

            BlockedContainer.AddChild(row);
        }
    }
    // Eclipsion End

    private void ShowToast(string message, bool toastError)
    {
        _toastGeneration++;
        var gen = _toastGeneration;

        ToastLabel.SetMessage(message, defaultColor: Color.White);
        ToastStrip.PanelOverride = toastError ? ToastStyleError : ToastStyleSuccess;
        ToastOverlay.Visible = true;

        Robust.Shared.Timing.Timer.Spawn(ToastDuration, () =>
        {
            if (gen != _toastGeneration)
                return;

            ToastOverlay.Visible = false;
        });
    }

    /// <summary>
    ///     Eclipsion - the list is rebuilt from several places and every one of them can drop the
    ///     selection, so the Block button is refreshed once here rather than at each early return.
    /// </summary>
    private void ApplyRecipientFilter()
    {
        RebuildRecipientList();
        UpdateBlockButton();
    }

    private void RebuildRecipientList()
    {
        var previousSelection = _selectedRecipient;
        RecipientList.Clear();

        if (_allRecipients.Count == 0)
        {
            _selectedRecipient = null;
            RecipientList.AddItem(Loc.GetString("money-transfer-ui-recipients-empty"), selectable: false);
            return;
        }

        var query = (SearchEdit.Text ?? string.Empty).Trim();
        IEnumerable<MoneyTransferRecipientState> filtered = _allRecipients;
        if (query.Length > 0)
        {
            filtered = _allRecipients.Where(r =>
                r.Name.Contains(query, StringComparison.OrdinalIgnoreCase)
                || r.Job.Contains(query, StringComparison.OrdinalIgnoreCase));
        }

        var list = filtered.ToList();
        foreach (var r in list)
        {
            var text = string.IsNullOrEmpty(r.Job)
                ? r.Name
                : Loc.GetString("money-transfer-ui-recipient-line", ("name", r.Name), ("job", r.Job));

            // Eclipsion - a blocked person stays in the list (you can still pay them) but is marked, so
            // nobody wonders why money from them never arrives.
            if (r.Blocked)
                text = Loc.GetString("money-transfer-ui-recipient-blocked", ("line", text));

            RecipientList.AddItem(text, metadata: r.Entity);
        }

        if (list.Count == 0)
        {
            _selectedRecipient = null;
            RecipientList.AddItem(Loc.GetString("money-transfer-ui-recipients-filter-empty"), selectable: false);
            return;
        }

        if (previousSelection is not { } selectedEntity)
        {
            _selectedRecipient = null;
            return;
        }

        for (var i = 0; i < RecipientList.Count; i++)
        {
            if (RecipientList[i].Metadata is not NetEntity entity || entity != selectedEntity)
                continue;

            RecipientList[i].Selected = true;
            _selectedRecipient = selectedEntity;
            return;
        }

        _selectedRecipient = null;
    }
}
