using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._EE.PlanetfallMap;

[GenerateTypedNameReferences]
public sealed partial class PlanetfallMapWindow : FancyWindow
{
    private const float InitialZoom = 0.5f;
    private const float ZoomStep = 0.25f;
    private const float MinZoom = 0.25f;
    private const float MaxZoom = 1.5f;

    private float _zoom = InitialZoom;

    public PlanetfallMapWindow()
    {
        RobustXamlLoader.Load(this);

        ZoomOutButton.OnPressed += _ => SetZoom(_zoom - ZoomStep);
        ZoomResetButton.OnPressed += _ => SetZoom(InitialZoom);
        ZoomInButton.OnPressed += _ => SetZoom(_zoom + ZoomStep);

        SetZoom(_zoom);
    }

    private void SetZoom(float zoom)
    {
        _zoom = Math.Clamp(zoom, MinZoom, MaxZoom);
        MapImage.TextureScale = new Vector2(_zoom, _zoom);
        ZoomLabel.Text = Loc.GetString("planetfall-map-zoom", ("percent", (int) (_zoom * 100)));
        ZoomOutButton.Disabled = _zoom <= MinZoom;
        ZoomInButton.Disabled = _zoom >= MaxZoom;
    }
}
