using Content.Shared._Goobstation.Research;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Goobstation.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleItem : LayoutContainer
{
    [Dependency] private IPrototypeManager _prototype = default!;

    // Public fields
    public TechnologyPrototype Prototype;
    public Action<TechnologyPrototype, ResearchAvailability>? SelectAction;
    public ResearchAvailability Availability;

    // Some visuals
    public static readonly Color DefaultColor = Color.FromHex("#2e2e2e");
    public static readonly Color DefaultBorderColor = Color.FromHex("#4972A1");
    public static readonly Color DefaultHoveredColor = Color.FromHex("#4972A1");

    public Color BackgroundColor = DefaultColor;
    public Color BorderColor = DefaultBorderColor;
    public Color HoveredColor = DefaultHoveredColor;
    public Color SelectedColor = DefaultHoveredColor;

    // Selection state
    private bool _isSelected = false;
    public bool IsSelected
    {
        get => _isSelected;
        set
        {
            if (_isSelected == value)
                return;
            _isSelected = value;
            UpdateColor();
        }
    }

    public FancyResearchConsoleItem(TechnologyPrototype proto, SpriteSystem sprite, ResearchAvailability availability)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Availability = availability;
        Prototype = proto;

        // Get the discipline for background color
        var discipline = _prototype.Index<TechDisciplinePrototype>(proto.Discipline);
        var disciplineColor = discipline.Color;

        ResearchDisplay.Texture = sprite.Frame0(proto.Icon);

        Button.OnPressed += Selected;
        Button.OnDrawModeChanged += UpdateColor;

        // Set colors - only border color varies by availability state
        var availabilityBorderColor = availability switch
        {
            ResearchAvailability.Researched => Color.FromHex("#2ab043"),
            ResearchAvailability.Available => Color.FromHex("#fab325"),
            ResearchAvailability.PrereqsMet => Color.FromHex("#91752f"),
            ResearchAvailability.Unavailable => Color.Crimson,
            _ => Color.Crimson
        };

        // Keep disciplines visually distinct while retaining enough contrast for the icon.
        BackgroundColor = Color.InterpolateBetween(disciplineColor, Color.Black, 0.55f);
        HoveredColor = Color.InterpolateBetween(BackgroundColor, Color.White, 0.25f);
        SelectedColor = Color.InterpolateBetween(BackgroundColor, Color.White, 0.4f);
        // Only border color varies by availability
        BorderColor = availabilityBorderColor;

        // Create rounded style box with 8px corner radius and thick border
        var roundedStyle = new RoundedStyleBoxFlat
        {
            BorderColor = BorderColor,
            BorderThickness = new Thickness(2.5f),
            CornerRadius = 8f
        };

        Panel.PanelOverride = roundedStyle;
        UpdateColor();
    }

    private void UpdateColor()
    {
        if (Panel.PanelOverride is RoundedStyleBoxFlat panel)
        {
            // Priority: Selected > Hovered > Normal
            if (IsSelected)
                panel.BackgroundColor = SelectedColor;
            else if (Button.IsHovered)
                panel.BackgroundColor = HoveredColor;
            else
                panel.BackgroundColor = BackgroundColor;

            panel.BorderColor = BorderColor;
        }
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        Button.OnPressed -= Selected;
    }

    private void Selected(BaseButton.ButtonEventArgs args)
    {
        SelectAction?.Invoke(Prototype, Availability);
    }
}

public sealed class DrawButton : Button
{
    public event Action? OnDrawModeChanged;

    public DrawButton()
    {
    }

    protected override void DrawModeChanged()
    {
        OnDrawModeChanged?.Invoke();
    }
}
