using System.Linq;
using Content.Client.Lathe;
using Content.Client.Research;
using Content.Client.Research.UI;
using Content.Shared._Goobstation.Research;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Goobstation.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyTechnologyInfoPanel : Control
{
    [Dependency] private IEntityManager _ent = default!;
    [Dependency] private IPrototypeManager _proto = default!;
    public TechnologyPrototype Prototype;
    public Action<TechnologyPrototype>? BuyAction;

    public FancyTechnologyInfoPanel(
        TechnologyPrototype proto,
        bool hasAccess,
        ResearchAvailability availability,
        SpriteSystem sprite,
        float softCapMultiplier)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var lathe = _ent.System<LatheSystem>();
        var research = _ent.System<ResearchSystem>();
        Prototype = proto;

        TechnologyNameLabel.Text = Loc.GetString(proto.Name);
        var discipline = _proto.Index<TechDisciplinePrototype>(proto.Discipline);
        DisciplineTexture.Texture = sprite.Frame0(discipline.Icon);
        TechnologyTierLabel.SetMessage(Loc.GetString(
            "research-console-tier-discipline-info",
            ("tier", proto.Tier),
            ("color", discipline.Color),
            ("discipline", Loc.GetString(discipline.Name))));

        TechnologyTexture.Texture = sprite.Frame0(proto.Icon);

        InitializePrerequisites(proto, research, sprite);

        InitializeRecipeUnlocks(proto, lathe, sprite);

        ResearchButton.ToolTip = !hasAccess
            ? Loc.GetString("research-console-no-access-popup")
            : null;

        ResearchButton.Text = availability == ResearchAvailability.Researched
            ? Loc.GetString("research-console-menu-server-researched-button")
            : ResearchButton.Text;

        Color? color = availability switch
        {
            ResearchAvailability.Researched => Color.LimeGreen,
            ResearchAvailability.PrereqsMet => Color.FromHex("#91752f"),
            ResearchAvailability.Unavailable => Color.Crimson,
            _ => null
        };
        var effectiveCost = (int) MathF.Round(proto.Cost * softCapMultiplier);
        TechnologyCostLabel.SetMessage(
            Loc.GetString("research-console-tech-cost-label", ("cost", effectiveCost)),
            defaultColor: color
        );

        ResearchButton.Disabled = !hasAccess || availability != ResearchAvailability.Available;

        ResearchButton.OnPressed += _ => BuyAction?.Invoke(proto);
    }

    private void InitializePrerequisites(TechnologyPrototype proto, ResearchSystem research, SpriteSystem sprite)
    {
        // Frontier: required techs always visible, label in required techs
        foreach (var child in RequiredTechContainer.Children.ToList())
        {
            if (child != NoPrereqLabel)
                RequiredTechContainer.RemoveChild(child);
        }
        // End Frontier: required techs always visible, label in required techs
        NoPrereqLabel.Visible = proto.TechnologyPrerequisites.Count == 0;
        foreach (var techId in proto.TechnologyPrerequisites)
        {
            var tech = _proto.Index(techId);
            var description = research.GetTechnologyDescription(tech, true, false, true);
            RequiredTechContainer.AddChild(new MiniTechnologyCardControl(tech, _proto, sprite, description));
        }
    }

    private void InitializeRecipeUnlocks(TechnologyPrototype proto, LatheSystem lathe, SpriteSystem sprite)
    {
        UnlocksContainer.RemoveAllChildren();
        foreach (var recipeId in proto.RecipeUnlocks)
        {
            var recipe = _proto.Index(recipeId);
            UnlocksContainer.AddChild(new MiniRecipeCardControl(proto, recipe, _proto, sprite, lathe));
        }
    }

}
