name: Benchmarks
on:
  workflow_dispatch:

concurrency: benchmarks

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.302
    - name: Run benchmarks
      working-directory: Content.Benchmarks
      env:
        ROBUST_BENCHMARKS_ENABLE_SQL: ${{ secrets.BENCHMARKS_WRITE_ADDRESS != '' && '1' || '0' }}
        ROBUST_BENCHMARKS_SQL_ADDRESS: ${{ secrets.BENCHMARKS_WRITE_ADDRESS }}
        ROBUST_BENCHMARKS_SQL_PORT: ${{ secrets.BENCHMARKS_WRITE_PORT }}
        ROBUST_BENCHMARKS_SQL_USER: ${{ secrets.BENCHMARKS_WRITE_USER }}
        ROBUST_BENCHMARKS_SQL_PASSWORD: ${{ secrets.BENCHMARKS_WRITE_PASSWORD }}
        ROBUST_BENCHMARKS_SQL_DATABASE: content_benchmarks
        GITHUB_SHA: ${{ github.sha }}
      run: dotnet run --filter '*' --configuration Release
